### ISSUE TITLE
reproduction problem

### ISSUE THREAD

**Issue by xiao-kong-long** [hongleir/SpaceFlow#2]
Hello hongleir, thanks for your excellent work, I don't know how you process the DLPFC datasets, I try to process it as the readme file do, but in preprocessing time, error occurs in `sc.pp.highly_variable_genes(adata, n_top_genes=n_top_genes, flavor='cell_ranger', subset=True)`

error is:
`Traceback (most recent call last):
  File "test_in_151676.py", line 28, in <module>
    sf.preprocessing_data(n_top_genes=3000)
  File "D:\pyprog\papers_code\SpaceFlow-master\SpaceFlow\SpaceFlow.py", line 134, in preprocessing_data
    sc.pp.highly_variable_genes(adata, n_top_genes=n_top_genes, flavor='cell_ranger', subset=True)
  File "E:\application\Anaconda3\envs\spaceflow_env\lib\site-packages\scanpy\preprocessing\_highly_variable_genes.py", line 440, in highly_variable_genes
    flavor=flavor,
  File "E:\application\Anaconda3\envs\spaceflow_env\lib\site-packages\scanpy\preprocessing\_highly_variable_genes.py", line 246, in _highly_variable_genes_single_batch
    np.r_[-np.inf, np.percentile(df['means'], np.arange(10, 105, 5)), np.inf],
  File "E:\application\Anaconda3\envs\spaceflow_env\lib\site-packages\pandas\core\reshape\tile.py", line 296, in cut
    ordered=ordered,
  File "E:\application\Anaconda3\envs\spaceflow_env\lib\site-packages\pandas\core\reshape\tile.py", line 414, in _bins_to_cuts
    f"Bin edges must be unique: {repr(bins)}.\n"
ValueError: Bin edges must be unique: array([          -inf, 1.00000000e-12, 1.00000000e-12, 1.00000000e-12,
       1.00000000e-12, 1.00000000e-12, 1.00000000e-12, 4.05749596e-04,
       1.01314564e-03, 2.31888015e-03, 5.40734371e-03, 1.16201913e-02,
       2.23582544e-02, 3.89729693e-02, 6.07338332e-02, 9.16402764e-02,
       1.37300240e-01, 2.13493855e-01, 3.88421885e-01, 5.81039639e+00,
                  inf]).
You can drop duplicate edges by setting the 'duplicates' kwarg`
   I have solved this problem by changing 'cell_ranger' to 'seurat_v3', but the ARI is 0.23, that  makes me doubt if I do anything wrong ?

**Comment by hongleir** [comment]
Hi Xiao-kong-long, I added  sc.pp.filter_genes(adata, min_cells=3) before `preprocessing_data` step to remove genes that only detected in less than 3 cells. That may solve your issue.

**Comment by xiao-kong-long** [comment]
> Hi Xiao-kong-long, I added `sc.pp.filter_genes(adata, min_cells=3)` before `sf = SpaceFlow.SpaceFlow(adata=adata)` step to remove genes that only detected in less than 3 cells. I also updated the README.md files so that you can copy it (remember to import scanpy before `sc.pp.filter_genes`: `import scanpy as sc`). Let me know if that solve your issue so that I can close the issue.

Problem have been solved perfectly as your instruction, thanks very much, have a nice day !
